parser: "@typescript-eslint/parser"

plugins:
  - "@typescript-eslint"

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier

env:
  node: true
  es6: true

rules:
  no-console: 0
  prefer-const: 0
  prefer-rest-params: 0
  no-redeclare: 0
  no-var: 0
  no-prototype-builtins: 0
  prefer-spread: 0
  "@typescript-eslint/explicit-function-return-type": 0
  "@typescript-eslint/explicit-member-accessibility": 0
  "@typescript-eslint/explicit-module-boundary-types": 0
  "@typescript-eslint/interface-name-prefix": 0
  "@typescript-eslint/ban-ts-ignore": 0
  "@typescript-eslint/no-var-requires": 0
  "@typescript-eslint/no-explicit-any": 0
  "@typescript-eslint/no-this-alias": 0
  "@typescript-eslint/no-parameter-properties": 0
  "@typescript-eslint/no-use-before-define": 0
  "@typescript-eslint/no-empty-function": 0
  "@typescript-eslint/no-unused-vars": 0
  